# Generated by Django 6.0.5 on 2026-06-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_course_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
