# Generated by Django 6.0.5 on 2026-06-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
