# Generated by Django 6.0.5 on 2026-06-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_embedding_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='students/photo.jpg', null=True, upload_to='students/'),
        ),
    ]
